version: '3.7'
services:

  mssqldata_test:
    image: microsoft/mssql-server-linux:latest
    entrypoint: /bin/bash

  mssql_test:
    image: microsoft/mssql-server-linux:latest
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      # we copy our scripts onto the container
      - ./database:/usr/src/app 
    # bash will be executed from that path, our scripts folder
    working_dir: /usr/src/app 
    # run the entrypoint.sh that will import the data AND sqlserver
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd 
      # don't use this if you don't want to persit data between docker up and down
    volumes_from:
      - mssqldata_test

networks:
  default:
    external:
      name: seoc_network